wiki-name: "Koding Framework Docs" 

# Directories
wiki-dir: "."
static-dir: "."
html-dir: "/Users/arslan/Sites/arslan.koding.com/website/docs/"
cvs-exclude: true

# Building
document-extensions: [.md, .mdown, .markdown, .wiki, .text]
generate-listing: always
listing-filename: "_list.html"

# Rendering
markdown:
  safe-mode: false
  output-format: xhtml1
  extensions: [codehilite, def_list, meta, headerid]
  extension-configs:
    codehilite:
      force_linenos: false
